---
name: Update members
on:
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout landscape
        uses: actions/checkout@v3
        with:
          path: landscape
      - name: Checkout landscape-tools
        uses: actions/checkout@v3
        with:
          repository: jmertic/landscape-tools
          path: landscape-tools
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r landscape-tools/requirements.txt
      - name: Run build
        working-directory: ./landscape
        run: |
          ../landscape-tools/landscapemembers.py
      - name: Save missing.csv file
        uses: actions/upload-artifact@v3
        with:
          name: missing-members
          path: ./landscape/missing.csv
      - name: Checkout landscapeapp
        uses: actions/checkout@v3
        with:
          repository: cncf/landscapeapp
          path: landscapeapp2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: cleanup yml files
        run: |
          cd landscapeapp2
          node tools/removePuppeteer
          npm install
          PROJECT_PATH=../landscape node tools/removeQuotes
          PROJECT_PATH=../landscape node tools/pruneExtraEntries
      - name: fix Accenture
        run: |
          cd landscape
          sed -e 's/https:\/\/www.crunchbase.com\/organization\/organization\//https:\/\/www.crunchbase.com\/organization\//'  < landscape.yml > l
          diff l landscape.yml || true
          mv l landscape.yml
          git add landscape.yml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          branch-suffix: timestamp
          path: ./landscape
          title: Update members
          labels: automated-build
          signoff: true
          committer: Hyperledger Bot <hyperledger-bot@hyperledger.org>
          author: Hyperledger Bot <hyperledger-bot@hyperledger.org>
          commit-message: Update members
